use anyhow::{bail, Context, Result};
use reqwest::{Client, Response};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::fs;
use std::path::PathBuf;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::process::{Child, ChildStdin, ChildStdout, Command};
use tokio::sync::Mutex;
use super::permissions::McpPermissions;
use super::sandbox::{wrap_command, SandboxConfig};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum McpTransport { Stdio, StreamableHttp }
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomMcpServerConfig { pub id:String,pub name:String,pub transport:McpTransport,pub command:Option<String>,#[serde(default)] pub args:Vec<String>,pub url:Option<String>,#[serde(default)] pub env:std::collections::HashMap<String,String>,#[serde(default)] pub permissions:McpPermissions,#[serde(default="default_true")] pub enabled:bool }
fn default_true()->bool{true}
#[derive(Debug,Default,Serialize,Deserialize)] pub struct CustomMcpStore{pub servers:Vec<CustomMcpServerConfig>}
fn filter_env(cfg:&CustomMcpServerConfig)->impl Iterator<Item=(&String,&String)>{cfg.env.iter().filter(move |(k,_)|cfg.permissions.environment.iter().any(|allowed|allowed==*k))}
fn expand_secret_ref(value:&str)->String{if let Some(key)=value.strip_prefix("${secret:").and_then(|x|x.strip_suffix('}')){return std::env::var(key).unwrap_or_default()}value.to_string()}
pub struct CustomMcpRegistry{path:PathBuf}
impl CustomMcpRegistry{pub fn new(project_root:impl Into<PathBuf>)->Result<Self>{let root=project_root.into();fs::create_dir_all(root.join(".agent"))?;Ok(Self{path:root.join(".agent").join("mcps.json")})}fn load(&self)->Result<CustomMcpStore>{if !self.path.exists(){return Ok(CustomMcpStore::default())}Ok(serde_json::from_str(&fs::read_to_string(&self.path)?)?)}fn save(&self,s:&CustomMcpStore)->Result<()> {fs::write(&self.path,serde_json::to_string_pretty(s)?)?;Ok(())}pub fn list(&self)->Result<Vec<CustomMcpServerConfig>>{Ok(self.load()?.servers)}pub fn add(&self,server:CustomMcpServerConfig)->Result<CustomMcpServerConfig>{if server.id.is_empty()||server.name.is_empty(){bail!("id and name are required")}server.permissions.validate()?;match server.transport{McpTransport::Stdio if server.command.as_deref().unwrap_or("").is_empty()=>bail!("stdio MCP requires command"),McpTransport::StreamableHttp if server.url.as_deref().unwrap_or("").is_empty()=>bail!("HTTP MCP requires url"),_=>{}}let mut s=self.load()?;s.servers.retain(|x|x.id!=server.id);s.servers.push(server.clone());self.save(&s)?;Ok(server)}pub fn remove(&self,id:&str)->Result<bool>{let mut s=self.load()?;let n=s.servers.len();s.servers.retain(|x|x.id!=id);self.save(&s)?;Ok(n!=s.servers.len())}pub fn set_enabled(&self,id:&str,enabled:bool)->Result<Option<CustomMcpServerConfig>>{let mut s=self.load()?;let x=match s.servers.iter_mut().find(|x|x.id==id){Some(x)=>x,None=>return Ok(None)};x.enabled=enabled;let r=x.clone();self.save(&s)?;Ok(Some(r))}pub fn get(&self,id:&str)->Result<Option<CustomMcpServerConfig>>{Ok(self.load()?.servers.into_iter().find(|x|x.id==id))}}

pub struct StdioMcpClient{child:Mutex<Child>,stdin:Mutex<ChildStdin>,stdout:Mutex<BufReader<ChildStdout>>,next_id:Mutex<u64>}
impl StdioMcpClient{pub async fn spawn(cfg:&CustomMcpServerConfig)->Result<Self>{let command=cfg.command.as_ref().context("missing stdio command")?;let sandbox=SandboxConfig::new(std::env::current_dir()?,cfg.permissions.clone())?;let (program,args)=wrap_command(&sandbox,command,&cfg.args)?;let mut cmd=Command::new(program);cmd.args(args).stdin(std::process::Stdio::piped()).stdout(std::process::Stdio::piped()).stderr(std::process::Stdio::inherit());for(k,v)in filter_env(cfg){cmd.env(k,expand_secret_ref(v));}let mut child=cmd.spawn().context("failed to start MCP server")?;let stdin=child.stdin.take().context("MCP stdin unavailable")?;let stdout=child.stdout.take().context("MCP stdout unavailable")?;Ok(Self{child:Mutex::new(child),stdin:Mutex::new(stdin),stdout:Mutex::new(BufReader::new(stdout)),next_id:Mutex::new(1)})}async fn request(&self,method:&str,params:Value)->Result<Value>{let mut id=self.next_id.lock().await;let request_id=*id;*id+=1;drop(id);let msg=json!({"jsonrpc":"2.0","id":request_id,"method":method,"params":params});{let mut input=self.stdin.lock().await;input.write_all((serde_json::to_string(&msg)?+"\n").as_bytes()).await?;input.flush().await?;}let mut line=String::new();self.stdout.lock().await.read_line(&mut line).await?;jsonrpc_result(serde_json::from_str(line.trim()).context("invalid MCP JSON-RPC response")?)}pub async fn initialize(&self)->Result<Value>{self.request("initialize",json!({"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"agent-workspace-hub","version":env!("CARGO_PKG_VERSION")}})).await}pub async fn tools_list(&self)->Result<Value>{self.request("tools/list",json!({})).await}pub async fn tools_call(&self,name:&str,arguments:Value)->Result<Value>{self.request("tools/call",json!({"name":name,"arguments":arguments})).await}}

pub struct StreamableHttpMcpClient{client:Client,url:String,next_id:Mutex<u64>,session_id:Mutex<Option<String>>,headers:std::collections::HashMap<String,String>}
impl StreamableHttpMcpClient{pub fn new(cfg:&CustomMcpServerConfig)->Result<Self>{let url=cfg.url.clone().context("missing streamable HTTP MCP url")?;let mut headers=std::collections::HashMap::new();for(k,v)in filter_env(cfg){headers.insert(k.clone(),expand_secret_ref(v));}Ok(Self{client:Client::new(),url,next_id:Mutex::new(1),session_id:Mutex::new(None),headers})}async fn request(&self,method:&str,params:Value)->Result<Value>{let mut id=self.next_id.lock().await;let request_id=*id;*id+=1;drop(id);let body=json!({"jsonrpc":"2.0","id":request_id,"method":method,"params":params});let mut req=self.client.post(&self.url).header("Content-Type","application/json").header("Accept","application/json, text/event-stream").json(&body);for(k,v)in&self.headers{req=req.header(k,v);}if let Some(session)=self.session_id.lock().await.clone(){req=req.header("Mcp-Session-Id",session);}let response=req.send().await?.error_for_status()?;if let Some(session)=response.headers().get("Mcp-Session-Id").and_then(|v|v.to_str().ok()){*self.session_id.lock().await=Some(session.to_string());}parse_http_response(response).await}pub async fn initialize(&self)->Result<Value>{self.request("initialize",json!({"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"agent-workspace-hub","version":env!("CARGO_PKG_VERSION")}})).await}pub async fn tools_list(&self)->Result<Value>{self.request("tools/list",json!({})).await}pub async fn tools_call(&self,name:&str,arguments:Value)->Result<Value>{self.request("tools/call",json!({"name":name,"arguments":arguments})).await}}
async fn parse_http_response(response:Response)->Result<Value>{let content_type=response.headers().get("content-type").and_then(|v|v.to_str().ok()).unwrap_or("").to_ascii_lowercase();if content_type.contains("application/json"){return jsonrpc_result(response.json().await?)}let text=response.text().await?;for line in text.lines(){if let Some(data)=line.strip_prefix("data:"){if let Ok(value)=serde_json::from_str::<Value>(data.trim()){return jsonrpc_result(value)}}}bail!("MCP HTTP response did not contain a JSON-RPC message")}
fn jsonrpc_result(response:Value)->Result<Value>{if let Some(error)=response.get("error"){bail!("MCP error: {error}")}Ok(response.get("result").cloned().unwrap_or(response))}
