use crate::mcp::{AuthMethod, ComposioProvider, Connector, ConnectorsMcp, MemoryMcp, MemoryScope, ProviderRegistry, SkillMcp, TaskPriority, TaskStatus, TasksMcp, WorkspaceMcp};
use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::path::PathBuf;
use std::sync::{Arc, RwLock};

#[derive(Debug, Deserialize)] struct RpcRequest { jsonrpc: String, id: Option<Value>, method: String, #[serde(default)] params: Value }
#[derive(Debug, Serialize)] struct RpcResponse { jsonrpc: &'static str, id: Option<Value>, result: Option<Value>, error: Option<Value> }

pub struct StdioMcpServer { skills: SkillMcp, workspace: WorkspaceMcp, memory: MemoryMcp, tasks: TasksMcp, connectors: ConnectorsMcp, providers: Arc<RwLock<ProviderRegistry>> }

impl StdioMcpServer {
    pub fn new(project_root: PathBuf) -> Result<Self> {
        let registry = Arc::new(RwLock::new(ProviderRegistry::default()));
        if std::env::var("COMPOSIO_API_KEY").is_ok() {
            if let Ok(provider) = ComposioProvider::from_env() {
                registry.write().map_err(|_| anyhow::anyhow!("provider registry lock poisoned"))?.register(Box::new(provider));
            }
        }
        Ok(Self { skills: SkillMcp::new(project_root.clone())?, workspace: WorkspaceMcp::new(project_root.clone())?, memory: MemoryMcp::new(project_root.clone())?, tasks: TasksMcp::new(project_root.clone())?, connectors: ConnectorsMcp::new(project_root)?, providers: registry })
    }
    pub fn provider_registry(&self) -> Arc<RwLock<ProviderRegistry>> { Arc::clone(&self.providers) }
    pub fn handle(&self, input: &str) -> Result<String> {
        let req: RpcRequest = serde_json::from_str(input)?;
        let result = match req.method.as_str() { "initialize" => json!({"protocolVersion":"2025-06-18","capabilities":{"tools":{}},"serverInfo":{"name":"agent-workspace-hub","version":env!("CARGO_PKG_VERSION")}}), "tools/list" => self.tools_list(), "tools/call" => self.call_tool(&req.params)?, _ => json!({"error":"method not found"}) };
        Ok(serde_json::to_string(&RpcResponse { jsonrpc:"2.0", id:req.id, result:Some(result), error:None })?)
    }
    fn tools_list(&self) -> Value { json!({"tools":[
        {"name":"skills.list","description":"List project-referenced skills","inputSchema":{"type":"object","properties":{}}}, {"name":"skills.read","description":"Read a project-referenced skill","inputSchema":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}, {"name":"skills.add","description":"Add an installed global skill","inputSchema":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}, {"name":"skills.remove","description":"Remove a project skill reference","inputSchema":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}, {"name":"skills.search","description":"Search globally installed skills","inputSchema":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}},
        {"name":"workspace.context","description":"Read project agent instructions","inputSchema":{"type":"object","properties":{}}}, {"name":"workspace.list_files","description":"List workspace files","inputSchema":{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}}, {"name":"workspace.read_file","description":"Read a workspace file","inputSchema":{"type":"object","properties":{"path":{"type":"string"}},"required":["path"]}},
        {"name":"memory.store","description":"Store project memory","inputSchema":{"type":"object","properties":{"id":{"type":"string"},"content":{"type":"string"},"scope":{"type":"string","enum":["Session","Project","Global"]},"tags":{"type":"array","items":{"type":"string"}}},"required":["id","content","scope"]}}, {"name":"memory.search","description":"Search memory","inputSchema":{"type":"object","properties":{"query":{"type":"string"},"scope":{"type":"string","enum":["Session","Project","Global"]}},"required":["query"]}}, {"name":"memory.get","description":"Get memory by id","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}}, {"name":"memory.delete","description":"Delete memory","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}},
        {"name":"tasks.create","description":"Create a task","inputSchema":{"type":"object","properties":{"id":{"type":"string"},"title":{"type":"string"},"description":{"type":"string"},"priority":{"type":"string","enum":["Low","Normal","High","Critical"]},"tags":{"type":"array","items":{"type":"string"}}},"required":["id","title","description"]}}, {"name":"tasks.list","description":"List tasks","inputSchema":{"type":"object","properties":{"status":{"type":"string","enum":["Todo","InProgress","Blocked","Done"]}}}}, {"name":"tasks.update","description":"Update a task","inputSchema":{"type":"object","properties":{"id":{"type":"string"},"status":{"type":"string","enum":["Todo","InProgress","Blocked","Done"]},"priority":{"type":"string","enum":["Low","Normal","High","Critical"]},"assignee":{"type":["string","null"]}},"required":["id"]}}, {"name":"tasks.delete","description":"Delete a task","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}},
        {"name":"connectors.list","description":"List connector metadata for this project","inputSchema":{"type":"object","properties":{}}}, {"name":"connectors.add","description":"Register connector metadata; never stores secrets","inputSchema":{"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"provider":{"type":"string"},"auth":{"type":"string","enum":["OAuth","ApiKey","None"]},"scopes":{"type":"array","items":{"type":"string"}},"enabled":{"type":"boolean"}},"required":["id","name","provider","auth"]}}, {"name":"connectors.enable","description":"Enable a connector","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}}, {"name":"connectors.disable","description":"Disable a connector","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}}, {"name":"connectors.remove","description":"Remove connector metadata","inputSchema":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}},
        {"name":"connector.providers","description":"List registered connector providers","inputSchema":{"type":"object","properties":{}}}, {"name":"connector.tools","description":"List tools exposed by a provider","inputSchema":{"type":"object","properties":{"provider":{"type":"string"}},"required":["provider"]}}, {"name":"connector.invoke","description":"Invoke a tool exposed by a provider","inputSchema":{"type":"object","properties":{"provider":{"type":"string"},"tool":{"type":"string"},"arguments":{"type":"object"}},"required":["provider","tool"]}}
    ]}) }
    fn call_tool(&self, p:&Value)->Result<Value>{
        let n=p.get("name").and_then(Value::as_str).unwrap_or_default(); let a=p.get("arguments").cloned().unwrap_or_else(||json!({}));
        let v=match n {
            "skills.list"=>serde_json::to_value(self.skills.list()?)?, "skills.read"=>serde_json::to_value(self.skills.read(a.get("name").and_then(Value::as_str).unwrap_or_default())?)?, "skills.add"=>{self.skills.add(a.get("name").and_then(Value::as_str).unwrap_or_default())?;json!({"ok":true})}, "skills.remove"=>json!({"removed":self.skills.remove(a.get("name").and_then(Value::as_str).unwrap_or_default())?}), "skills.search"=>serde_json::to_value(self.skills.search_global(a.get("query").and_then(Value::as_str).unwrap_or_default())?)?,
            "workspace.context"=>serde_json::to_value(self.workspace.context()?)?, "workspace.list_files"=>serde_json::to_value(self.workspace.list_files(a.get("path").and_then(Value::as_str).unwrap_or("."))?)?, "workspace.read_file"=>serde_json::to_value(self.workspace.read_file(a.get("path").and_then(Value::as_str).unwrap_or_default())?)?,
            "memory.store"=>{let s=parse_scope(a.get("scope").and_then(Value::as_str));serde_json::to_value(self.memory.store(strval(&a,"id"),strval(&a,"content"),s,strings(&a,"tags"))?)?}, "memory.search"=>serde_json::to_value(self.memory.search(a.get("query").and_then(Value::as_str).unwrap_or_default(),a.get("scope").and_then(Value::as_str).map(parse_scope))?)?, "memory.get"=>serde_json::to_value(self.memory.get(a.get("id").and_then(Value::as_str).unwrap_or_default())?)?, "memory.delete"=>json!({"deleted":self.memory.delete(a.get("id").and_then(Value::as_str).unwrap_or_default())?}),
            "tasks.create"=>serde_json::to_value(self.tasks.create(strval(&a,"id"),strval(&a,"title"),strval(&a,"description"),parse_priority(a.get("priority").and_then(Value::as_str)),strings(&a,"tags"))?)?, "tasks.list"=>serde_json::to_value(self.tasks.list(a.get("status").and_then(Value::as_str).map(parse_status))?)?, "tasks.update"=>serde_json::to_value(self.tasks.update(a.get("id").and_then(Value::as_str).unwrap_or_default(),a.get("status").and_then(Value::as_str).map(parse_status),a.get("priority").and_then(Value::as_str).map(|x|parse_priority(Some(x))),a.get("assignee").map(|x|x.as_str().map(str::to_string)))?)?, "tasks.delete"=>json!({"deleted":self.tasks.delete(a.get("id").and_then(Value::as_str).unwrap_or_default())?}),
            "connectors.list"=>serde_json::to_value(self.connectors.list()?)?, "connectors.add"=>{let c=Connector{id:strval(&a,"id"),name:strval(&a,"name"),provider:strval(&a,"provider"),auth:parse_auth(a.get("auth").and_then(Value::as_str)),scopes:strings(&a,"scopes"),enabled:a.get("enabled").and_then(Value::as_bool).unwrap_or(true)};serde_json::to_value(self.connectors.add(c)?)?}, "connectors.enable"=>serde_json::to_value(self.connectors.set_enabled(a.get("id").and_then(Value::as_str).unwrap_or_default(),true)?)?, "connectors.disable"=>serde_json::to_value(self.connectors.set_enabled(a.get("id").and_then(Value::as_str).unwrap_or_default(),false)?)?, "connectors.remove"=>json!({"removed":self.connectors.remove(a.get("id").and_then(Value::as_str).unwrap_or_default())?}),
            "connector.providers"=>{let r=self.providers.read().map_err(|_|anyhow::anyhow!("provider registry lock poisoned"))?;json!(r.providers())}, "connector.tools"=>{let provider=a.get("provider").and_then(Value::as_str).unwrap_or_default();let r=self.providers.read().map_err(|_|anyhow::anyhow!("provider registry lock poisoned"))?;serde_json::to_value(r.tools(provider)?)?}, "connector.invoke"=>{let provider=a.get("provider").and_then(Value::as_str).unwrap_or_default();let tool=a.get("tool").and_then(Value::as_str).unwrap_or_default();let args=a.get("arguments").cloned().unwrap_or_else(||json!({}));let r=self.providers.read().map_err(|_|anyhow::anyhow!("provider registry lock poisoned"))?;serde_json::to_value(r.invoke(provider,tool,args)?)?},
            _=>json!({"error":"unknown tool"})}; Ok(json!({"content":[{"type":"text","text":serde_json::to_string(&v)?}]}))
    }
}
fn strval(a:&Value,k:&str)->String{a.get(k).and_then(Value::as_str).unwrap_or_default().to_string()} fn strings(a:&Value,k:&str)->Vec<String>{a.get(k).and_then(Value::as_array).map(|x|x.iter().filter_map(Value::as_str).map(str::to_string).collect()).unwrap_or_default()} fn parse_scope(x:Option<&str>)->MemoryScope{match x.unwrap_or("Project"){"Session"=>MemoryScope::Session,"Global"=>MemoryScope::Global,_=>MemoryScope::Project}} fn parse_status(x:&str)->TaskStatus{match x{"InProgress"=>TaskStatus::InProgress,"Blocked"=>TaskStatus::Blocked,"Done"=>TaskStatus::Done,_=>TaskStatus::Todo}} fn parse_priority(x:Option<&str>)->TaskPriority{match x.unwrap_or("Normal"){"Low"=>TaskPriority::Low,"High"=>TaskPriority::High,"Critical"=>TaskPriority::Critical,_=>TaskPriority::Normal}} fn parse_auth(x:Option<&str>)->AuthMethod{match x.unwrap_or("None"){"OAuth"=>AuthMethod::OAuth,"ApiKey"=>AuthMethod::ApiKey,_=>AuthMethod::None}}
